version: "3.5"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - SERVER_PORT=80
  api_arm:
    build:
      context: .
      dockerfile: Dockerfile.Arm
    ports:
      - "8080:80"
    environment:
      - SERVER_PORT=80
